name: "app"

on:
  schedule:
    - cron: "0 12 * * 3"
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "**.dart"
      - "./*.yaml"
      - .github/workflows/pipeline.yaml
      - .github/workflows/app.yaml
      - ".github/actions/**"

# call the base workflow with the package path
jobs:
  detect-sdk:
    strategy:
      matrix:
        package:
          - dart_app
          - flutter_app
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      os: ${{ matrix.os }}

  force-sdk-flutter:
    strategy:
      matrix:
        package:
          - flutter_app
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      force-sdk: "flutter"
      os: ${{ matrix.os }}

  force-sdk-dart:
    strategy:
      matrix:
        package:
          - dart_app
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      force-sdk: "dart"
      os: ${{ matrix.os }}

  branch-sdk-flutter:
    strategy:
      matrix:
        package:
          - flutter_app
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-branch: "beta"

  branch-sdk-dart:
    strategy:
      matrix:
        package:
          - dart_app
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-branch: "beta"

  version-sdk-flutter:
    strategy:
      matrix:
        package:
          - flutter_app
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-version: "3.38.5"

  version-sdk-dart:
    strategy:
      matrix:
        package:
          - dart_app
        os:
          - ubuntu-latest
          - macos-latest
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-version: "3.10.1"
