name: "package"

on:
  schedule:
    - cron: "0 12 * * 3"
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "**.dart"
      - "./*.yaml"
      - .github/workflows/pipeline.yaml
      - .github/workflows/package.yaml
      - ".github/actions/**"

# call the base workflow with the package path
jobs:
  detect-sdk:
    strategy:
      matrix:
        package:
          - dart_package_template
          - flutter_package
          - dart_codegen
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      min-publish-score: 160

  force-sdk-flutter:
    strategy:
      matrix:
        package:
          - flutter_package
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      force-sdk: "flutter"
      min-publish-score: 160

  force-sdk-dart:
    strategy:
      matrix:
        package:
          - dart_package_template
          - dart_codegen
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      force-sdk: "dart"
      min-publish-score: 160

  branch-sdk-flutter:
    strategy:
      matrix:
        package:
          - flutter_package
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-branch: "beta"
      min-publish-score: 160

  branch-sdk-dart:
    strategy:
      matrix:
        package:
          - dart_package_template
          - dart_codegen
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-branch: "beta"
      min-publish-score: 160

  version-sdk-flutter:
    strategy:
      matrix:
        package:
          - flutter_package
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-version: "3.38.5"
      min-publish-score: 160

  version-sdk-dart:
    strategy:
      matrix:
        package:
          - dart_package_template
          - dart_codegen
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/${{ matrix.package }}"
      sdk-version: "3.10.1"
      min-publish-score: 160
