name: "Flutter/Dart"
description: "Reusable CI pipeline workflow for Flutter and Dart projects"

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."
      sdk-branch:
        required: false
        type: string
        default: "stable"
      sdk-version:
        required: false
        type: string
      force-sdk:
        required: false
        type: string
        description: "Override detected SDK (flutter/dart) with this value, for testing purposes. Must be 'flutter' or 'dart'."
      os:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "The OS to run the workflow on. Can be overridden by the caller workflow for testing purposes."
      min-publish-score:
        required: false
        type: number
        default: 0
        description: "Minimum publish score required to pass the publish step. Set to 0 to disable publish score check."
      skip-publish:
        required: false
        type: boolean
        default: false
        description: "Whether to skip the publish step entirely, even the dry run. Useful for packages that are not meant to be published, or to speed up CI when publish checks are not needed."
      skip-docs:
        description: "Whether to skip generating docs"
        required: false
        type: boolean
        default: false
      skip-tests:
        description: "Whether to skip running tests"
        required: false
        type: boolean
        default: false
      skip-format:
        description: "Whether to skip code formatting"
        required: false
        type: boolean
        default: false
      skip-analyze:
        description: "Whether to skip code analysis"
        required: false
        type: boolean
        default: false
      skip-build:
        description: "Whether to skip the build step"
        required: false
        type: boolean
        default: true

jobs:
  checks:
    name: "checks"
    runs-on: ${{ inputs.os }}
    outputs:
      sdk: ${{ steps.check-sdk.outputs.sdk }}
      do_tests: ${{ steps.check-tests.outputs.do_tests }}
      do_codegen: ${{ steps.check-codegen.outputs.do_codegen }}
      do_publish: ${{ steps.check-publish.outputs.do_publish }}
      do_docs: ${{ steps.check-docs.outputs.do_docs }}
      docs_path: ${{ steps.check-docs.outputs.docs_path }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      # Check whether to use flutter/dart CLI
      - id: check-sdk
        run: |
          if [ -n "${{ inputs.force-sdk }}" ]; then
            echo "Forcing SDK to ${{ inputs.force-sdk }}.";
            sdk=${{ inputs.force-sdk }}
          elif [ -f "${{ inputs.path }}/pubspec.yaml" ] && grep -q "flutter:" "${{ inputs.path }}/pubspec.yaml"; then
            echo "Flutter SDK detected.";
            sdk=flutter
          else
            echo "Flutter SDK not detected.";
            sdk=dart
          fi
          echo "sdk=$sdk" >> $GITHUB_OUTPUT
      # Skip if no test directory
      - id: check-tests
        run: |
          if [ "${{ inputs.skip-tests }}" = "true" ]; then
            echo "skip-tests input is true, skipping tests.";
            do_tests=0
          elif [ ! -d "${{ inputs.path }}/test" ]; then
            echo "No test directory found, skipping tests.";
            do_tests=0
          else
            echo "Test directory found, will run tests.";
            do_tests=1
          fi
          echo "do_tests=$do_tests" >> $GITHUB_OUTPUT
      # Skip if no build_runner dependency
      - id: check-codegen
        run: |
          if [ -f "${{ inputs.path }}/pubspec.yaml" ] && grep -q "build_runner:" "${{ inputs.path }}/pubspec.yaml"; then
            echo "build_runner dependency found, will run codegen.";
            do_codegen=1
          else
            echo "No build_runner dependency found, skipping codegen.";
            do_codegen=0
          fi
          echo "do_codegen=$do_codegen" >> $GITHUB_OUTPUT
      # Skip if `publish_to` is set to `none`
      - id: check-docs
        run: |
          DOCS_PATH="${{ inputs.path }}/doc"
          # Check whether docs folder exists
          if [ -d "${{ github.workspace }}/$DOCS_PATH" ]; then
            echo "do_docs=1" >> $GITHUB_OUTPUT
          else
            echo "Docs folder not found at $DOCS_PATH"
            echo "do_docs=0" >> $GITHUB_OUTPUT
          fi

          echo "docs_path=${{ github.workspace }}/$DOCS_PATH" >> $GITHUB_OUTPUT

      - id: check-publish
        run: |

          if [ "${{ inputs.skip-publish }}" = "true" ]; then
            echo "skip-publish input is true, skipping publish step.";
            do_publish=0
          # accept both `publish_to: none`, `publish_to: 'none'`, and `publish_to: "none"`
          elif [ -f "${{ inputs.path }}/pubspec.yaml" ] && grep -Eq "publish_to:[[:space:]]?(['\"]?)?none\1" "${{ inputs.path }}/pubspec.yaml"; then
            echo "Skipping publish step.";
            do_publish=0
          else
            echo "Running publish step.";
            do_publish=1
          fi

          echo "do_publish=$do_publish" >> $GITHUB_OUTPUT

  install:
    name: "install"
    runs-on: ${{ inputs.os }}
    needs: [checks]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      - uses: $/.github/actions/setup-sdk
        with:
          sdk: ${{ needs.checks.outputs.sdk }}
          sdk-version: ${{ inputs.sdk-version }}
          sdk-branch: ${{ inputs.sdk-branch }}
          cache: ${{ needs.checks.outputs.sdk == 'flutter' }}

      - name: "Get dependencies"
        run: ${{ needs.checks.outputs.sdk }} pub get
        working-directory: ${{ inputs.path }}

  format:
    name: "format"
    runs-on: ${{ inputs.os }}
    if: inputs.skip-format == false
    needs: [install, checks]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5
      - uses: $/.github/actions/setup-sdk
        with:
          sdk: ${{ needs.checks.outputs.sdk }}
          sdk-version: ${{ inputs.sdk-version }}
          sdk-branch: ${{ inputs.sdk-branch }}
          cache: ${{ needs.checks.outputs.sdk == 'flutter' }}

      - name: "Get dependencies"
        run: ${{ needs.checks.outputs.sdk }} pub get
        working-directory: ${{ inputs.path }}

      - name: "dart format"
        run: |
          echo "Checking Dart formatting...\nFiles displayed below:"
          dart format -o none --set-exit-if-changed ./lib/
          dart format -o none --set-exit-if-changed ./bin/
          if [ ${{ needs.checks.outputs.do_tests }} -eq 1 ]; then dart format -o none --set-exit-if-changed ./test/; fi
          echo "No formatting issues found."
        working-directory: ${{ inputs.path }}

  analyze:
    name: "analyze"
    runs-on: ${{ inputs.os }}
    if: inputs.skip-analyze == false
    needs: [install, checks]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5
      - uses: $/.github/actions/setup-sdk
        with:
          sdk: ${{ needs.checks.outputs.sdk }}
          sdk-version: ${{ inputs.sdk-version }}
          sdk-branch: ${{ inputs.sdk-branch }}
          cache: ${{ needs.checks.outputs.sdk == 'flutter' }}

      - name: "Get dependencies"
        run: ${{ needs.checks.outputs.sdk }} pub get
        working-directory: ${{ inputs.path }}

      - name: Run codegen
        if: needs.checks.outputs.do_codegen == 1
        run: ${{ needs.checks.outputs.sdk }} pub run build_runner build --delete-conflicting-outputs
        working-directory: ${{ inputs.path }}

      - name: Run analysis
        run: |
          if [ -d "./lib" ]; then ${{ needs.checks.outputs.sdk }} analyze --fatal-warnings ./lib/; fi
          if [ -d "./bin" ]; then ${{ needs.checks.outputs.sdk }} analyze --fatal-warnings ./bin/; fi
        working-directory: ${{ inputs.path }}

  test:
    needs: [install, checks]
    runs-on: ${{ inputs.os }}
    if: needs.checks.outputs.do_tests == 1
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5
      - uses: $/.github/actions/setup-sdk
        with:
          sdk: ${{ needs.checks.outputs.sdk }}
          sdk-version: ${{ inputs.sdk-version }}
          sdk-branch: ${{ inputs.sdk-branch }}
          cache: ${{ needs.checks.outputs.sdk == 'flutter' }}

      - name: "Get dependencies"
        run: ${{ needs.checks.outputs.sdk }} pub get
        working-directory: ${{ inputs.path }}

      - name: Run codegen
        if: needs.checks.outputs.do_codegen == 1
        run: ${{ needs.checks.outputs.sdk }} pub run build_runner build --delete-conflicting-outputs
        working-directory: ${{ inputs.path }}

      - name: Run tests
        run: ${{ needs.checks.outputs.sdk }} test --reporter=expanded ./test/
        working-directory: ${{ inputs.path }}

  docs:
    name: "docs"
    if: ${{
        cancelled() == false && needs.checks.outputs.do_docs == 1 && inputs.skip-docs == false &&
        ( needs.analyze.result == 'success' || needs.analyze.result == 'skipped' ) &&
        ( needs.format.result == 'success' || needs.format.result == 'skipped' )
      }}
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    runs-on: ubuntu-latest
    needs: [ checks, analyze, format ]

    steps:
      - uses: actions/checkout@v5
      - uses: $/.github/actions/setup-sdk
        with:
          sdk: ${{ needs.checks.outputs.sdk }}
          sdk-version: ${{ inputs.sdk-version }}
          sdk-branch: ${{ inputs.sdk-branch }}
          cache: ${{ needs.checks.outputs.sdk == 'flutter' }}
          package-path: ${{ inputs.path }}

      - name: dartdoc
        run: |
          flutter pub global activate dartdoc
          flutter pub global run dartdoc

      - name: Upload docs artifact
        # only if triggered on main push or release action OR has label 'ci: publish-docs'
        if: |
          (
            (github.event_name == 'push' && github.ref == 'refs/heads/main') || 
            github.event_name == 'workflow_dispatch' ||
            contains(github.event.pull_request.labels.*.name, 'ci: publish-docs')
          )
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: ${{ needs.checks.outputs.docs_path }}

      - name: Instructions
        run: |
          echo "To view docs, download the file above, unzip it and run the following in its folder:"
          echo "  > dart pub global activate dhttpd"
          echo "  > dart pub global run dhttpd --path ./"

  publish-dry-run:
    runs-on: ${{ inputs.os }}
    # Needs dart or flutter job to complete successfully, only skipped if either is failed, but not skipped
    needs: [checks, test, analyze, format]
    if: ${{
        cancelled() == false && needs.checks.outputs.do_publish == 1 &&
        ( needs.test.result == 'success' || needs.test.result == 'skipped' ) &&
        ( needs.analyze.result == 'success' || needs.analyze.result == 'skipped' ) &&
        ( needs.format.result == 'success' || needs.format.result == 'skipped' )
      }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      - uses: $/.github/actions/setup-sdk
        with:
          sdk: ${{ needs.checks.outputs.sdk }}
          sdk-version: ${{ inputs.sdk-version }}
          sdk-branch: ${{ inputs.sdk-branch }}
          cache: ${{ needs.checks.outputs.sdk == 'flutter' }}

      - name: "Get dependencies"
        run: ${{ needs.checks.outputs.sdk }} pub get
        working-directory: ${{ inputs.path }}

      - name: Run codegen
        if: needs.checks.outputs.do_codegen == 1
        run: ${{ needs.checks.outputs.sdk }} pub run build_runner build --delete-conflicting-outputs
        working-directory: ${{ inputs.path }}

      - name: Publish to pub.dev (dry run)
        run: ${{ needs.checks.outputs.sdk }} pub publish --dry-run
        working-directory: ${{ inputs.path }}

      - name: Run Pana ("server-side" analysis used by pub.dev)
        if: inputs.min-publish-score > 0
        run: |
          # Install pana globally
          ${{ needs.checks.outputs.sdk }} pub global activate pana
          # Run pana and extract the overall score
          PANA=$(pana -j . 2> /dev/null);
          PANA_SCORE=$(echo $PANA | jq -r 'select(has("scores")) | .scores.grantedPoints');
          PANA_MAX_SCORE=$(echo $PANA | jq -r 'select(has("scores")) | .scores.maxPoints');
          PANA_SUMMARY=$(echo $PANA | jq -r 'select(has("report")) | .report.sections[].summary');
          echo "Score: $PANA_SCORE/$PANA_MAX_SCORE (minimum required: ${{inputs.min-publish-score}})"
          echo -e "\n$PANA_SUMMARY"
          if (( $PANA_SCORE < ${{inputs.min-publish-score}} )); then echo -e "\n\nThe minimum score was not met!"; exit 1; fi
        working-directory: ${{ inputs.path }}
