name: "single"

on:
  schedule:
    - cron: "0 12 * * 3"
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "**.dart"
      - "./*.yaml"
      - .github/workflows/pipeline.yaml
      - .github/workflows/single.yaml
      - ".github/actions/**"

# call the base workflow with the package path
jobs:
  dart_package:
    uses: ./.github/workflows/pipeline.yaml
    with:
      path: "packages/dart_package_template"
      min-publish-score: 160
